# Generated by Django 2.0.7 on 2018-07-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180725_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1),
        ),
    ]
