# Generated by Django 2.0.7 on 2018-07-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_food_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('PIZZA', 'pizza'), ('SUB', 'sub'), ('SALAD', 'salad'), ('PASTA', 'pasta'), ('DINNER', 'dinner platter')], default='PIZZA', max_length=1),
        ),
    ]
