# Generated by Django 2.0.7 on 2018-07-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180726_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='choose_toppings',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='NO', max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('PIZZA', 'pizza'), ('SUB', 'sub'), ('SALAD', 'salad'), ('PASTA', 'pasta'), ('DINNER', 'dinner platter')], default='PIZZA', max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='toppings',
            field=models.CharField(choices=[('NONE', 'none'), ('PEPPERONI', 'pepperoni'), ('SAUSAGE', 'sausage'), ('MUSHROOMS', 'mushrooms'), ('ONIONS', 'onions'), ('HAM', 'ham'), ('CANADIAN BACON', 'canadian bacon'), ('PINEAPPLE', 'pineapple'), ('EGGPLANT', 'egglplant'), ('TOMATO & BASIL', 'tomato & basil'), ('GREEN PEPPERS', 'green peppers'), ('HAMBURGER', 'hamburger'), ('SPINACH', 'spinach'), ('ARTICHOKE', 'artichoke'), ('BUFFALO CHICKEN', 'buffalo chicken'), ('BARBECUE CHICKEN', 'barbecue chicken'), ('ANCHOVIES', 'anchovies'), ('BLACK OLIVES', 'black olives'), ('FRESH GARLIC', 'fresh garlic'), ('ZUCCHINI', 'zucchini')], default='NONE', max_length=50),
        ),
    ]
