# Generated by Django 2.0.7 on 2018-07-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180726_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description of the food item', max_length=1000),
        ),
    ]
