# Generated by Django 2.0.7 on 2018-07-26 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180726_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=20)),
                ('food_type', models.CharField(choices=[('PIZZA', 'pizza'), ('SUB', 'sub'), ('SALAD', 'salad'), ('PASTA', 'pasta'), ('DINNER', 'dinner platter')], default='PIZZA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order_Number'),
        ),
    ]
