# Generated by Django 2.0.7 on 2018-07-31 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20180728_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='toppings',
            field=models.CharField(choices=[('NONE', 'none'), ('PEPPERONI', 'pepperoni'), ('SAUSAGE', 'sausage'), ('MUSHROOMS', 'mushrooms'), ('ONIONS', 'onions'), ('HAM', 'ham'), ('CANADIAN BACON', 'canadian bacon'), ('PINEAPPLE', 'pineapple'), ('EGGPLANT', 'egglplant'), ('TOMATO & BASIL', 'tomato & basil'), ('GREEN PEPPERS', 'green peppers'), ('HAMBURGER', 'hamburger'), ('SPINACH', 'spinach'), ('ARTICHOKE', 'artichoke'), ('BUFFALO CHICKEN', 'buffalo chicken'), ('BARBECUE CHICKEN', 'barbecue chicken'), ('ANCHOVIES', 'anchovies'), ('BLACK OLIVES', 'black olives'), ('FRESH GARLIC', 'fresh garlic'), ('ZUCCHINI', 'zucchini')], default='NONE', max_length=50),
        ),
    ]
