# Generated by Django 2.0.7 on 2018-07-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='toppings',
            field=models.CharField(max_length=200),
        ),
    ]
