# Generated by Django 2.0.7 on 2018-08-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20180731_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity_ordered',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
