# Generated by Django 2.0.3 on 2018-08-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotrees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trees',
            name='lat',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='trees',
            name='lng',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
    ]
