# Generated by Django 2.0.3 on 2018-08-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotrees', '0002_auto_20180813_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart', models.BooleanField(default=False)),
                ('diamont', models.BooleanField(default=False)),
                ('flag', models.BooleanField(default=False)),
                ('basic_cup', models.BooleanField(default=False)),
                ('golde_cup', models.BooleanField(default=False)),
                ('star', models.BooleanField(default=False)),
            ],
        ),
    ]
