# Generated by Django 2.0.3 on 2018-08-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gotrees', '0004_badges_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badges',
            old_name='golde_cup',
            new_name='golden_cup',
        ),
    ]
