# Generated by Django 2.0.3 on 2018-08-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gotrees', '0005_auto_20180813_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='trees',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='gotrees.Profiles'),
        ),
    ]
