# Generated by Django 2.0.3 on 2018-08-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotrees', '0007_trees_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
