# Generated by Django 2.0.3 on 2018-08-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotrees', '0012_auto_20180817_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
