# Generated by Django 2.0.3 on 2018-08-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotrees', '0013_offers_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='coupon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
