# Generated by Django 2.0.3 on 2018-07-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addition', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DinnerPlatters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinner', models.CharField(max_length=40)),
                ('small', models.DecimalField(decimal_places=2, max_digits=5)),
                ('large', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=40)),
                ('pizza_type', models.CharField(max_length=40, null=True)),
                ('pizza_size', models.CharField(max_length=15, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('username', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pastas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pizzas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegPizzaPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.DecimalField(decimal_places=2, max_digits=5)),
                ('large', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_price', to='orders.Pizzas')),
            ],
        ),
        migrations.CreateModel(
            name='Salads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salad', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SiciPizzaPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.DecimalField(decimal_places=2, max_digits=5)),
                ('large', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sicilian_price', to='orders.Pizzas')),
            ],
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=30)),
                ('small', models.DecimalField(decimal_places=2, max_digits=5)),
                ('large', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='pizza_toppings',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='orders.Toppings'),
        ),
        migrations.AddField(
            model_name='orders',
            name='sub_additions',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='orders.Additions'),
        ),
    ]
