# Generated by Django 2.0.3 on 2018-07-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pizza_toppings',
            field=models.ManyToManyField(related_name='orders', to='orders.Toppings'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sub_additions',
            field=models.ManyToManyField(related_name='orders', to='orders.Additions'),
        ),
    ]
