# Generated by Django 2.0.3 on 2018-07-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180726_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='additions',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
            preserve_default=False,
        ),
    ]
