# Generated by Django 2.0.3 on 2018-07-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_additions_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(default='draft', max_length=10),
            preserve_default=False,
        ),
    ]
