# Generated by Django 2.0.3 on 2018-07-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='pizza_size',
            new_name='size',
        ),
    ]
