# Generated by Django 2.0.3 on 2018-07-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_confirmations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmations',
            name='pizza_toppings',
            field=models.ManyToManyField(blank=True, related_name='confirmations', to='orders.Toppings'),
        ),
        migrations.AlterField(
            model_name='confirmations',
            name='sub_additions',
            field=models.ManyToManyField(blank=True, related_name='confirmations', to='orders.Additions'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pizza_toppings',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.Toppings'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sub_additions',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.Additions'),
        ),
    ]
