# Generated by Django 2.0.3 on 2018-07-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180731_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmations',
            name='pizza_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='confirmations',
            name='size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pizza_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
